services:
  cafe_backend:
    build:
      context: ./
    container_name: cafe_backend
    ports:
      - "8089:8080"  # 8080 es el puerto que escucha Node dentro del contenedor
    env_file:
      - ./.env
    restart: always
    networks:
      - cafe-net

  flutter_web:
    build:
      context: .
      dockerfile: ./frontend-nginx/Dockerfile
    container_name: cafe-frontend-nginx
    ports:
      - "446:443"
    volumes:
      - /home/pi/docker/projects/backend-cafe/certs:/etc/nginx/certs:ro
    depends_on:
      - cafe_backend
    restart: always
    networks:
      - cafe-net

networks:
  cafe-net:
    external: true
